### ISSUE TITLE
GDPR Article 25 : Privacy By Design and By default

### ISSUE THREAD

**Issue by rzr** [LINCnil/Guide-RGPD-du-developpeur#1]
Bonjour,

Premièrement merci de l'initiative.

Une suggestion, il serait intéressant aussi de couvrir l'article 25 
(qui a mes yeux est le plus important).

Les recommandations pour les développeurs de systèmes ou service,
sont bienvenues.

Pour ma part je peux partager quelques tips pour ce qui concerne l'IoT:

https://purl.org/rzr/privacy

**Comment by MbiLINC** [comment]
Bonjour,

Merci pour vos retours ! 
L'article 25 est notamment mentionné dans la fiche 2 "Préparer son développement". Mais peut-être pouvons-nous le développer davantage dans le guide. 

N'hésitez pas à nous faire des suggestions directement via Pull requests, nous serons ravis de pouvoir étudier vos propositions pour alimenter ce guide, notamment sur la partie IoT. 

Bonne journée à vous.
