### ISSUE TITLE
Cookies exemptés de consentement 

### ISSUE THREAD

**Issue by smknstd** [LINCnil/Guide-RGPD-du-developpeur#14]
Une fiche devrait expliciter le besoin de demande de consentement pour les différents types de cookies. J'aurai aimé trouver cette information sur https://github.com/LINCnil/Guide-RGPD-du-developpeur/blob/master/12-Informer%20les%20utilisateurs.md par exemple.

![Screenshot_2020-01-30 Cookies comment mettre mon site web en conformité CNIL](https://user-images.githubusercontent.com/2412608/73473393-f863e480-438c-11ea-91d8-c584e4e53ffe.png)

Source: https://www.cnil.fr/fr/cookies-comment-mettre-mon-site-web-en-conformite

**Comment by LaboCNIL** [comment]
Bonjour, 

Effectivement pour le moment les informations concernant les cookies sont un peu disséminées. Il y en a une partie dans [la fiche 15](https://github.com/LINCnil/Guide-RGPD-du-developpeur/blob/3e86d1f01474c64b448103143a571aad68a9291c/15-Prendre%20en%20compte%20les%20bases%20l%C3%A9gales%20dans%20l%E2%80%99impl%C3%A9mentation%20technique.md#le-cas-sp%C3%A9cifique-des-cookies-et-autres-traceurs) et en partie dans la [fiche 16](https://github.com/LINCnil/Guide-RGPD-du-developpeur/blob/3e86d1f01474c64b448103143a571aad68a9291c/16-Mesurer%20la%20fr%C3%A9quentation.md#obtenir-le-consentement). Il est prévu de faire une fiche spécialement sur les cookies, mais ce ne sera sans doute pas avant que la [consultation relative à ce sujet](https://www.cnil.fr/fr/la-cnil-lance-une-consultation-publique-sur-son-projet-de-recommandation-cookies-et-autres-traceurs) soit terminée. Je vous invite d’ailleurs à y participer! 

Je vous signale au passage que la page que vous avez mise en lien est disponible à titre informatif uniquement et que son contenu est obsolète (en raison de la consultation en cours).

**Comment by smknstd** [comment]
Merci pour la réponse. La fiche en tous cas avait le mérite d'être très clair :) J'éspère que le guide evoluera dans ce sens.

**Comment by LaboCNIL** [comment]
Bonjour,

La nouvelle révision du guide contient une fiche dédiée à l'usage des traceurs :
https://github.com/LINCnil/Guide-RGPD-du-developpeur/blob/master/16-Analyser%20les%20traceurs.md

N'hésitez pas à ouvrir un nouveau ticket si des informations sont manquantes.

**Comment by smknstd** [comment]
Excellent !
