### ISSUE TITLE
Force-push sur public master ?

### ISSUE THREAD

**Issue by yvesb** [LINCnil/Guide-RGPD-du-developpeur#16]
Bonjour,

sauf erreur, il semble qu'il y ait eu un force-push sur la branche master publique qui a réécrit son historique ? ( https://github.com/LINCnil/Guide-RGPD-du-developpeur/compare/3c01855862864870fa5a7f32a1a46324be9092ee..c3e4394117c0ad5983d8e432a4f465af7284fea0 ).

Du coup, tous les PR sont fermés (ça semble lié) et les forks desynchronisés. Enfin c'est ce que je constate de mon côté impossible de rapatrier le uspstream dans mon dépôt, d'ailleurs sur le dépôt LINCnil actuel il n'y a visiblement plus qu'un commit dans l'historique à la date d'aujourd'hui (4/02).

Bon, la bonne nouvelle, c'est que la dernière modif apparaissant dans le lien ci-dessus répond à ma question #4 Merci.

Mais sinon pour la resynchro des clones distants et les PR, il semble y avoir un souci?

Merci d'avance pour votre retour

**Comment by LaboCNIL** [comment]
Bonjour, 
 
Effectivement, nous avons du procéder à un force-push pour rectifier des points d’historique ce qui a malheureusement provoqué la fermeture des PR actuelles.
 
En ce qui concerne les PR, le README va être mis à jour pour expliciter le process, mais pour respecter la politique donnée plus haut, les modifications seront ajoutée via un compte CNIL. Cependant les personnes ayant proposé les modifications seront créditées comme co-auteurs et un fichier des contributeurs sera mis à jour et présent dans les releases PDF. 
 
Il serait plus simple d’utiliser un flow standard, mais ces conditions sont nécessaires pour permettre cette expérience d’écriture collaborative, et nous espérons vous voir continuer à participer à ce processus ! 
 
Effectivement lors du force-push, nous en avons profité pour répondre à la #4 (point précisé dans le dernier commit).
 
Bonne journée !
