### ISSUE TITLE
Fiche 0, point 5 - incompréhenssion

### ISSUE THREAD

**Issue by waldo2188** [LINCnil/Guide-RGPD-du-developpeur#18]
Fiche "Fiche n°0 : Développer en conformité avec le RGPD" point N°5, la phrase 
```
(même si celui-ci plus octroyé par la CNIL depuis l’entrée en application du RGPD)
```
 n'est pas clair du tout.

Le label de est-il encore octroyé ou non ?

**Comment by yvesb** [comment]
Bonjour,

les labels ne sont plus délivrés par la CNIL depuis l'entrée en application du RGPD, cf https://www.cnil.fr/fr/transition-vers-le-rgpd-des-labels-la-certification

Il manque effectivement visiblement "**_n'est_**" dans la phrase ("[...] même si celui-ci **_n'est_** plus octoyé [...]"). Ceci a fait l'objet d'un pull request #5 , mais tous les pull requests antérieurs au 04/02 ont été fermés à cette même date (cf #16 ).

Cdt
