### ISSUE TITLE
Delta entre Github et le site de la CNIL

### ISSUE THREAD

**Issue by Theosakamg** [LINCnil/Guide-RGPD-du-developpeur#2]
Bonjour,

Dans le chapitre [2. Préparer son développement](https://www.cnil.fr/fr/preparer-son-developpement), section "Outils et pratiques" de la version Web publié sur le site de la CNIL.

> Vous trouverez facilement sur internet des listes de bonnes pratiques pour votre langage de programmation favori. [Par exemple](http://wiki.sei.cmu.edu/confluence/display/seccode/SEI+CERT+Coding+Standards)[ici pour C, C++ ou Java](https://wiki.sei.cmu.edu/confluence/display/seccode/SEI+CERT+Coding+Standards). Pour le développement d’application web, des guides de bonnes pratiques spécifiques existent, tels que ceux publiés par  [l’OWASP.](https://www.owasp.org/index.php/Main_Page)

Il manque un espace, de plus le lien semble dupliqué dans une version http et une https.

Cependant la version sur Github est conforme.
> Vous trouverez facilement sur internet des listes de bonnes pratiques pour votre langage de programmation favori. Par exemple [ici](https://wiki.sei.cmu.edu/confluence/display/seccode/SEI+CERT+Coding+Standards) pour C, C++ ou Java. Pour le développement d’application web, des guides de bonnes pratiques spécifiques existent, tels que ceux publiés par [l’OWASP.](https://www.owasp.org/index.php/Main_Page)

Je ne sais pas ci ceci est lié à **Pandoc** ou au process de déploiement ?

**Comment by LaboCNIL** [comment]
Bonjour, 

Merci de l’information, nous allons en informer le Webmaster du site de la CNIL.
