### ISSUE TITLE
Droits et bases légales

### ISSUE THREAD

**Issue by Cecile-999** [LINCnil/Guide-RGPD-du-developpeur#22]
Bonjour,

Il me semble que dans le tableau des droits, le droit à l'effacement n'est pas assez nuancé. On peut toujours demandé à être effacé lorsqu'on est sous contrat et qu'on ne souhaite pas payer sa facture, mais cela ne marche pas vraiment. De la même manière, on peut également toujours demandé à être effacé d'un traitement de lutte contre la fraude, mais il faut mettre en balance les intérêts. Je propose le tableau suivant, qu'en pensez-vous?

Cordialement, 
[synthèse_droits-licéité-V3.docx](https://github.com/LINCnil/Guide-RGPD-du-developpeur/files/4244246/synthese_droits-liceite-V3.docx)

**Comment by LaboCNIL** [comment]
Bonjour,

La nouvelle version du guide contient une version légèrement révisée du tableau présentant les bases légales et notamment des précisions sur le droit à l'effacement :
https://github.com/LINCnil/Guide-RGPD-du-developpeur/blob/master/15-Prendre%20en%20compte%20les%20bases%20l%C3%A9gales%20dans%20l%E2%80%99impl%C3%A9mentation%20technique.md

N'hésitez pas à réouvrir ce ticket avec de nouveaux commentaires si des éléments restent à clarifier.
