### ISSUE TITLE
[Fiche 18] Mise à jour des sources (ANSSI/OWASP)

### ISSUE THREAD

**Issue by VPrax** [LINCnil/Guide-RGPD-du-developpeur#33]
Hello ! 

Plusieurs sources utilisées semblent avoir été mises à jour au courant de l'année sans que cela soit reflété dans le guide.

Pour la partie ANSSI : 
1. (Bug) Dans la partie "Bruteforce", la ressource "ANSSI : Recommandations de sécurité relatives aux mots de passe" est un lien vers l'ancien guide, qui a depuis été dé-publié,
[Page de présentation du guide le remplaçant](https://www.ssi.gouv.fr/guide/recommandations-relatives-a-lauthentification-multifacteur-et-aux-mots-de-passe/) (Avantage de cette page : le lien "Calculer la force d'un mot de passe")
[Le guide v2](https://www.ssi.gouv.fr/uploads/2021/10/anssi-guide-authentification_multifacteur_et_mots_de_passe.pdf) (En bonus : la collaboration CNIL dans la v2 ;) )
2.  (Enhancement) Le guide utilisé dans les sources "ANSSI: Recommandations pour la sécurisation des sites web" a lui aussi été mis à jour. Le périmètre du guide a cependant été modifié. Ainsi, si la section concernant [la prévention contre les attaques XSS](https://www.ssi.gouv.fr/uploads/2013/05/anssi-guide-recommandations_mise_en_oeuvre_site_web_maitriser_standards_securite_cote_navigateur-v2.0.pdf#section.5.2) s'en retrouve plus étoffée, celle concernant les [SQLi](https://www.ssi.gouv.fr/uploads/2013/05/anssi-guide-recommandations_mise_en_oeuvre_site_web_maitriser_standards_securite_cote_navigateur-v2.0.pdf#section.2.2) a été laissée de côté, au profil d'un lien vers les [cheatsheets de l'OWASP](https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html) (lien aussi référencé dans la source de l'OWASP)
À noter cependant : même si le guide a été mis à jour, les deux versions sont toujours présentées dans les [bonnes pratiques : "Sécuriser un site web"](https://www.ssi.gouv.fr/particulier/guide/recommandations-pour-la-securisation-des-sites-web/)
3. (Feature/Enhancement) Dépréciation il y a quelques mois de toute la rubrique des "Notes d'information" du site du CERT-FR (Ce n'est pas en soi un problème, mais on pourrait imaginer une mention '(Non maintenu) CERT-FR: XXX' par soucis de clareté)

(Feature/Enhancement) Pour ce qui est de l'OWASP, il s'agit plus d'une question "de philosophie" que de réelle mise à jour des sources. La ressource concernant les [SQLi](https://owasp.org/www-project-top-ten/2017/A1_2017-Injection.html) vient du TOP10 2017; 4 ans après, elle fait toujours partie du [TOP10 (2021)](https://owasp.org/Top10/A03_2021-Injection/), la mise à jour permettrait juste de rappeler que c'est toujours d'actualité (et aussi d'avoir une esthétique plus... moderne? du site source)

Merci pour tout le travail que vous avez fait et continuez à faire !

**Comment by LaboCNIL** [comment]
Bonjour et merci pour ces recommandations très précises!

Nous avons essayé de les prendre au maximum en compte dans nos dernières modifications. N'hésitez pas à nous proposer vos contributions sous la forme de pull request!
