### ISSUE TITLE
Mise à jour nom branche principale

### ISSUE THREAD

**Issue by anthonygraignic** [LINCnil/Guide-RGPD-du-developpeur#35]
Bonjour,

Merci pour ces fiches très complètes et détaillées !
J'ai vu que ce repo utilise toujours `master` comme nom de branche principale. Est-il possible de changer pour `main` ou un autre nom ?
https://github.com/github/renaming

Bonne journée

**Comment by LaboCNIL** [comment]
C'est fait, merci!
