### ISSUE TITLE
Mesure d'audience : expliciter la situation de Google Analytics

### ISSUE THREAD

**Issue by yvesb** [LINCnil/Guide-RGPD-du-developpeur#4]
Bonjour,

Avant tout, merci pour l'élaboration de ce guide

Dans la page sur la mesure de fréquentation, il est indiqué 

> La plupart des grandes offres de mesures d'audience ne rentrent pas dans le périmètre de l'exemption, et ce, quelle que soit leur configuration

Ne serait-il pas possible d'être explicite sur le cas Google Analytics ? La CNIL n'a pas vocation à prescrire des solutions, certes, mais étant donné la prépondérance de GA, il serait probablement pertinent de préciser sa situation (on comprend que GA n'est pas exempté de consentement, Google étant susceptible - quelle que soit la configuration - d'utiliser des données à ses propres fins, mais cette lecture n'est sans doute pas une évidence). 

Au même titre que la CNIL suggère nommément une solution compatible (Matomo anciennement Piwik - Pull Request ouvert à ce sujet pour préciser -), il serait utile de clarifier explicitement au moins le cas de Google Analytics.

Merci, et bonne journée

**Comment by LaboCNIL** [comment]
Bonjour, 
Merci de ce retour. Une information plus précise a été publiée, comme vous avez pu le remarquer!
