### ISSUE TITLE
Mentionner la base des faiblesses de code CWE et ses relations avec OWASP

### ISSUE THREAD

**Issue by tmotsch42** [LINCnil/Guide-RGPD-du-developpeur#43]
La base de données des faiblesses du code CWE est souvent négligée. Pourtant, il est lié au célèbre top 10 Owasp et intégré aux outils de test de sécurité des applications statiques (SAST) comme sonarqube et autres Snyks. Par conséquent, leur contribution à l'obtention d'un code de confiance dans la partie Build-Share est très importante. Il est bien sûr également important d'utiliser en permanence des outils comme Falco pour rendre les images de confiance disponibles dans le registre interne de la partie Share-Run. 
https://cwe.mitre.org/data/definitions/1344.html

**Comment by LaboCNIL** [comment]
Bonjour et merci pour cette contribution.

La référence a été ajoutée en fin de la fiche suivante :
https://raw.githubusercontent.com/LINCnil/Guide-RGPD-du-developpeur/main/09-Ma%C3%AEtriser%20vos%20biblioth%C3%A8ques%20et%20vos%20SDK.md

Bien cordialement
