### ISSUE TITLE
Utiliser un titre moins stéréotypé dans lequel les développeuses peuvent aussi se reconnaitre

### ISSUE THREAD

**Issue by marionldev** [LINCnil/Guide-RGPD-du-developpeur#44]
Utiliser un titre moins stéréotypé dans lequel les développeuses peuvent aussi se reconnaitre

Suggestions
Guide RGPD des développeurs et développeuses
Guide RGPD des équipes de développement

**Comment by floriancastelain** [comment]
https://fr.wikipedia.org/wiki/Genre_neutre_en_fran%C3%A7ais_moderne_et_contemporain#Statut_du_masculin_comme_%C3%A9ventuel_marqueur_du_neutre

Que vous soyez d'accord ou non n'y change rien. Qu'il y ai (beaucoup) de reproche à faire à l'Académie Française, soit. Mais aujourd'hui, c'est elle qui est supposé "définir la langue", si une telle chose existe et afin de faire en sorte que tous les francophones utilisent une base commune, nous devrions suivre ses prérogatives.

**Comment by cbm-fchabanois** [comment]
"L'équipe de développement" est aussi français et il n'y a pas d'ambiguité sur l'auditoire.

**Comment by merciremi** [comment]
@floriancastelain L'Académie ne définie pas la langue, elle témoigne seulement de son évolution. L'évolution, elle, se fait via les usages, et ce que propose @marionldev est justement un usage aujourd'hui répandu (que vous le vouliez ou non).

**Comment by pierreboudes** [comment]
Ce serait dommage que ce soit justement LINC qui rate la raison principale de cet heureux changement. Comme le dit le psycholinguiste Pascal Gygax «Un langage qui utilise le masculin comme valeur par défaut est exclusif ». https://www.lemonde.fr/idees/article/2021/09/05/un-langage-qui-utilise-le-masculin-comme-valeur-par-defaut-est-exclusif_6093464_3232.html 
Je m'occupe d'un master qui est composé pour plus de la moitié de futures développeuses et elles méritent qu'on les considère pleinement, surtout lorsque l'on souhaite les sensibiliser au RGPD. La forme des choix.

**Comment by GaspardPO** [comment]
Bonjour, 

si on considère que l’Académie française fait foi, j'ai vérifié sur leur dictionnaire :
Les termes inclusifs **dev**  et **developpeureuse** n'existent pas.
Le féminin **développeuse** n'existe pas non plus.

Mais le masculin **Développeur** non plus !

Par contre les termes **[équipe](https://www.dictionnaire-academie.fr/article/A9E2415)**, **[de](https://www.dictionnaire-academie.fr/article/A9D0138)** et **[développement](https://www.dictionnaire-academie.fr/article/A9D2201)** proposés par @marionldev  existent dans le dictionnaire.

Donc ne serait ce que pour se mettre en conformité avec l'Académie, il faut changer de titre de guide.

Et en plus d'être conforme avec l'Académie ça ferait un titre plus inclusif et ça permettrait de fermer cette issue.

(on peut attendre la nouvelle version pour avoir développeur, mais vu que là c'est la version de travail en cours depuis 1936, avec la lettre D mise à jour en 1992, je pense qu'on risque d'attendre un bon moment avant d'avoir "développeur")

**Comment by floriancastelain** [comment]
Je propose donc, au lieu de "développeur" et "développeuse", "développeur.e.s" ! 

Blague mise à part, je n'ai pas accès à la totalité de l'article sur le monde, tant pis pour moi.

Quant au fait que l'usage de "développeuse" soit répandu, je suppose que cela dépend du système dans lequel évolue les personnes. Personne ne me l'a jamais sortie et ce n'est pas faute d'avoir des femmes dans le domaine de l'assurance.

Mais soit, si tout le monde le souhaite. (Je continuerai à utiliser le masculin pour ma part, ne m'en veuillez pas 😛 )

**Comment by floriancastelain** [comment]
> @floriancastelain L'Académie ne définie pas la langue, elle témoigne seulement de son évolution. L'évolution, elle, se fait via les usages, et ce que propose @marionldev est justement un usage aujourd'hui répandu (que vous le vouliez ou non).

PS: je suis dubitatif. Si on en croit le monde

>  à donner des règles certaines à [la langue française] 

https://www.lemonde.fr/culture/article/2014/04/11/a-quoi-sert-l-academie-francaise_4400052_3246.html

**Comment by LaboCNIL** [comment]
Bonjour et merci pour l'ensemble de vos suggestions.

Vos contributions ont été intégrées dans le guide. Nous devons encore mettre à jour l'image correspondante... et changer le nom du répertoire désormais en "Guide RGPD de l'équipe de développement" !

Bien cordialement.
