### ISSUE TITLE
Dans la release 2.1, le PDF n'a pas été ajouté aux assets.

### ISSUE THREAD

**Issue by aaribaud** [LINCnil/Guide-RGPD-du-developpeur#51]
La documentation pointe vers les releases pour un PDF pré-généré, mais il n'est pas présent dans la release 2.1. Il est en revanche présent dans les releases précédentes.

**Comment by LaboCNIL** [comment]
Effectivement, c'est un oubli. Merci de nous l'avoir notifié!
