### ISSUE TITLE
Améliorer la mise en page du site statique pour mobile 

### ISSUE THREAD

**Issue by pachevalier** [LINCnil/Guide-RGPD-du-developpeur#8]
La lisibilité du site statique sur mobile pourrait être améliorée avec une police plus grosse et des lignes plus courtes 

![Screenshot_20200129-103809](https://user-images.githubusercontent.com/3227753/73345672-c36c6a80-4284-11ea-9ef1-344151c2caf8.png)

**Comment by LaboCNIL** [comment]
Bonjour, 
Effectivement, un tag meta manquant,
Merci du retour!
